write file in py2/py3 compatible manner
addressing py3 error
Traceback (most recent call last):
...
  File "/usr/lib/python3.4/site-packages/dnf-plugins/debug.py", line 93, in run
    fobj.write(DEBUG_VERSION)
  File "/usr/lib64/python3.4/gzip.py", line 343, in write
    self.crc = zlib.crc32(data, self.crc) & 0xffffffff
TypeError: 'str' does not support the buffer interface